services:
    bot-shitfuck:
        container_name: bot-shitfuck
        build:
            context: ../
            dockerfile: ./src/Dockerfile
        # restart: always
        ports: 
            - "3016:3016"
        env_file:
            - app.env

